---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dev.vector
  resources:
  - vectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.vector
  resources:
  - vectors/finalizers
  verbs:
  - update
- apiGroups:
  - dev.vector
  resources:
  - vectors/status
  verbs:
  - get
  - patch
  - update
