# permissions for end users to edit vectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-editor-role
rules:
- apiGroups:
  - dev.vector
  resources:
  - vectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.vector
  resources:
  - vectors/status
  verbs:
  - get
