# permissions for end users to view vectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-viewer-role
rules:
- apiGroups:
  - dev.vector
  resources:
  - vectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dev.vector
  resources:
  - vectors/status
  verbs:
  - get
