package sinks

type SinkType string

const (
	ApacheMetrics            SinkType = "apache_metrics"
	AWSECSMetrics            SinkType = "aws_ecs_metrics"
	AWSKinesisFirehose       SinkType = "aws_kinesis_firehose"
	AWSS3                    SinkType = "aws_s3"
	AWSSQS                   SinkType = "aws_sqs"
	DatadogAgent             SinkType = "datadog_agent"
	DemoLogs                 SinkType = "demo_logs"
	DNSStap                  SinkType = "dnstap"
	DockerLogs               SinkType = "docker_logs"
	EventStoreDBMetrics      SinkType = "eventstoredb_metrics"
	Exec                     SinkType = "exec"
	File                     SinkType = "file"
	Fluent                   SinkType = "fluent"
	GCPPubSub                SinkType = "gcp_pubsub"
	HerokuLogplex            SinkType = "heroku_logs"
	HostMetrics              SinkType = "host_metrics"
	HTTP                     SinkType = "http"
	InternalLogs             SinkType = "internal_logs"
	InternalMetrics          SinkType = "internal_metrics"
	JournalD                 SinkType = "journald"
	Kafka                    SinkType = "kafka"
	KubernetesLogs           SinkType = "kubernetes_logs"
	Logstash                 SinkType = "logstash"
	MongoDBMetrics           SinkType = "mongodb_metrics"
	NATS                     SinkType = "nats"
	NGINXMetrics             SinkType = "nginx_metrics"
	PostgreSQLMetrics        SinkType = "postgresql_metrics"
	PrometheusRemoteWrite    SinkType = "prometheus_remote_write"
	PrometheusScrape         SinkType = "prometheus_scrape"
	Redis                    SinkType = "redis"
	Socket                   SinkType = "socket"
	SplunkHTTPEventCollector SinkType = "splunk_hec"
	StatsD                   SinkType = "statsd"
	STDIN                    SinkType = "stdin"
	Syslog                   SinkType = "syslog"
	Vector                   SinkType = "vector"
)
